### ISSUE TITLE
USER STORY: Develop a Wireframe for the User Interface

### ISSUE THREAD

**Issue by Julia-cloudname** [JWalshe86/2312-hackathon-team5#1]
As a web **developer**, I want **to create a detailed wireframe** for the project's user interface, so that **the team can visualize and understand the layout, design elements, and user flow before the actual development begins**.

Tasks:

- [x] Conduct a brief competitive analysis to see how similar interfaces are structured.
- [x] Define the basic layout and utilize the chosen wireframing tool (Balsamiq, Marvelapp), focusing on the placement of major elements like navigation bars, content sections and footer.

**Comment by alanjameschapman** [comment]
Wireframes created for mobile devices - see commit #14.
