### ISSUE TITLE
USER STORY: develop PDF vouchers

### ISSUE THREAD

**Issue by Julia-cloudname** [JWalshe86/2312-hackathon-team5#38]
As a user, I want to save some PDF documents with details of the gift (address of the shop, % of discount, the name of gift, price), so I can use it for buying presents

**Comment by alanjameschapman** [comment]
Initial vouchers created on 15/12/23.

Link [here](https://www.canva.com/design/DAF3Epw95Oo/5IM2kOi60pZrJoc8ysBYKg/view?utm_content=DAF3Epw95Oo&utm_campaign=designshare&utm_medium=link&utm_source=editor)

[vouchers.pdf](https://github.com/JWalshe86/2312-hackathon-team5/files/13692383/vouchers.pdf)
[vouchers.zip](https://github.com/JWalshe86/2312-hackathon-team5/files/13692384/vouchers.zip)
